language: node_js
node_js:
 - 0.6
install:
 - echo "deb http://packages.groonga.org/ubuntu/ $(lsb_release --short --codename) universe" | sudo tee /etc/apt/sources.list.d/groonga.list
 - sudo apt-get update
 - sudo apt-get -y --allow-unauthenticated install groonga-keyring
 - sudo apt-get -y --force-yes install libgroonga-dev
 - npm install
